### ISSUE TITLE
Error when saving without Shared folder

### ISSUE THREAD

**Issue by LnLcFlx** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#28]
Prevent the user from enabling WebDAV without a Shared folder 'None' as to avoid this error pop-up
```
500 - OK
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color webdav 2>&1' with exit code '1': debian: Data failed to compile: ---------- Rendering SLS 'base:omv.deploy.webdav.default' failed: Jinja error: list indices must be integers or slices, not str Traceback (most recent call last): File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl output = template.render(**decoded_context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render self.environment.handle_exception() File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception raise rewrite_traceback_stack(source=source) File "<template>", line 35, in top-level template code File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call return __context.call(__obj, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__ return self.loader.run(run_func, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
or fix it to allow 'None'.

**Comment by ryecoaaron** [comment]
Available on 7.0.5 in the repo now.
